#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { buildComparisonGraph } = require('./utils/comparison_graph');

function loadTriplets(csvPath) {
    const txt = fs.readFileSync(csvPath, 'utf8').trim();
    const lines = txt.split('\n');
    const header = lines.shift();
    const rows = lines.map(l => l.split(','));
    // Expect: participant,anchor,optionA,optionB,chosen,strength,timestamp
    return rows.map(cols => ({ participant: cols[0], anchor: cols[1], optionA: cols[2], optionB: cols[3], chosen: cols[4], strength: cols[5] }));
}

function findSparsePairs(graph, n = 50) {
    const nodes = graph.nodes();
    const sparse = [];
    for (let i = 0; i < nodes.length; i++) {
        for (let j = i + 1; j < nodes.length; j++) {
            const w = graph.getEdgeWeight(nodes[i], nodes[j]) || 0;
            if (w < 3) sparse.push({ pair: [nodes[i], nodes[j]], weight: w });
        }
    }
    sparse.sort((a, b) => a.weight - b.weight);
    return sparse.slice(0, n).map(s => s.pair);
}

function topVariancePlaceholder(ids, n = 50) {
    // Placeholder: randomly pick pairs among ids
    const pairs = [];
    for (let i = 0; i < n; i++) {
        const a = ids[Math.floor(Math.random() * ids.length)];
        const b = ids[Math.floor(Math.random() * ids.length)];
        if (a !== b) pairs.push([a, b].sort());
    }
    return pairs;
}

async function main() {
    const tripletsPath = path.join('data', 'triplets.csv');
    if (!fs.existsSync(tripletsPath)) {
        console.error('No triplet data found at', tripletsPath);
        process.exit(1);
    }

    console.log('\n' + '='.repeat(70));
    console.log('  UNCERTAINTY ANALYSIS (LIGHTWEIGHT)');
    console.log('='.repeat(70));

    const triplets = loadTriplets(tripletsPath);
    console.log(`\n  Loaded ${triplets.length} triplet comparisons`);

    const graph = buildComparisonGraph(triplets.map(t => [t.participant, t.anchor, t.optionA, t.optionB]));
    console.log('  Built comparison graph');

    // Strategy: sparse pairs + high-variance placeholder
    const sparsePairs = findSparsePairs(graph, 40);
    const ids = graph.nodes();
    const variancePairs = topVariancePlaceholder(ids, 40);

    // Merge and dedupe, limit to 50
    const seen = new Set();
    const merged = [];
    for (const p of sparsePairs.concat(variancePairs)) {
        const key = p.join('|||');
        if (!seen.has(key)) {
            merged.push(p);
            seen.add(key);
        }
        if (merged.length >= 50) break;
    }

    const output = {
        timestamp: new Date().toISOString(),
        targetPairs: merged,
        note: 'Generated by compute_uncertainty.js (lightweight). Replace with bootstrap-based analysis for better accuracy.'
    };

    const outPath = path.join('data', 'target_pairs.json');
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, JSON.stringify(output, null, 2));

    console.log(`\n  ✓ Saved ${merged.length} target pairs to ${outPath}\n`);
    console.log('='.repeat(70) + '\n');
}

if (require.main === module) main().catch(e => { console.error(e); process.exit(1); });
module.exports = { main };
